name: SAST Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package -f app/pom.xml

    - name: Pipeline scan
      uses: veracode/Veracode-pipeline-scan-action@v1.0.16
      with:
          vid: "vera01ei-${{ secrets.VERACODE_API_ID}}"
          vkey: "vera01es-${{ secrets.VERACODE_API_KEY}}"
          file: app/target/verademo.war
          debug: 1
    - name: Download the Pipeline Scanner
      run: |
            curl https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip -o pipeline-scan.zip
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip
    - name: Run Pipeline Scanner
      run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "vera01ei-${{secrets.VERACODE_API_ID}}" --veracode_api_key "vera01es-${{secrets.VERACODE_API_KEY}}" --file "app/target/verademo.war" 
