name: SAST Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn package

    - name: Verify Veracode API credentials
      id: verify_api_creds
      uses: veracode/github-actions-integration-helper@v0.1.3
      with:
          action: validateVeracodeApiCreds
          token: ${{ github.event.client_payload.token }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          appname: Verademo-teams

    - name: Pipeline scan
      uses: veracode/Veracode-pipeline-scan-action@v1.0.16
      with:
          vid: "vera01ei-${{ secrets.VERACODE_API_ID}}"
          vkey: "vera01es-${{ secrets.VERACODE_API_KEY}}"
          file: target/verademo.war
          debug: 1
